### ISSUE TITLE
Simplify grant start and end dates

### ISSUE THREAD

**Issue by hampelm** [detroitledger/gnl_profile#66]
Currently, grant start and end dates are available in the API like so:

```
        field_year: 
          date_type: "datetime"
          timezone: "America/Detroit"
          timezone_db: "America/Detroit"
          value: "2012-01-01 05:00:00"
          value2: "2017-01-01 05:00:00"
```

It would be more convenient to simply have `field_start_date` and `field_end_date` properties (or any similar name) with a commonly-formatted string, eg `YYYY-MM-DD HH:mm Z`.
